### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by agoora** [ethicalvats/weak-keys-generator#1]
Hello,
How to use this script?
What dependencies and what version of python?

**Comment by ethicalvats** [comment]
python 3.7
just install following packages using pip, ecdsa and sha3
if you want to make gcloud biquery calls
https://cloud.google.com/bigquery/docs/reference/libraries#client-libraries-install-python

The script it based on following paper https://www.ise.io/casestudies/ethercombing/

**Comment by agoora** [comment]
Unfortunately I don't quite understand how it works.
Maybe you could explain.
Thanks.

**Comment by ethicalvats** [comment]
sure shoot your questions ??
